version: '3.7'

services:

  django:
    container_name: timesheet-django
    build:
      context: .
      dockerfile: django.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/src
    command: python3 manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: timesheet-postgres
    image: library/postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database/:/tmp/database/

  pgadmin:
    image: dpage/pgadmin4
    container_name: timesheet-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  postgres-data:
