# Generated by Django 3.2.9 on 2022-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('street', models.CharField(max_length=250, verbose_name='street')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('country', models.CharField(max_length=250, verbose_name='county')),
                ('zip_code', models.IntegerField(verbose_name='zip code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
