# Generated by Django 3.2.9 on 2022-01-15 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20220115_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.client', verbose_name='client')),
                ('lead_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='lead employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
