# Generated by Django 3.2.9 on 2021-12-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
            ],
            options={
                'db_table': 'core_daily_time_sheet',
            },
        ),
        migrations.CreateModel(
            name='TimeSheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='hours')),
                ('overtime_hours', models.FloatField(default=0, verbose_name='overtime hours')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('daily_time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheet_reports', to='timesheet.dailytimesheet', verbose_name='daily time sheet')),
            ],
            options={
                'db_table': 'core_time_sheet_report',
                'default_related_name': 'time_sheet_reports',
            },
        ),
    ]
