# Generated by Django 3.2.9 on 2022-01-15 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0002_dailytimesheet_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimesheet',
            name='employee',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_time_sheets', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
    ]
