# Generated by Django 3.2.9 on 2022-01-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220115_1927'),
        ('timesheet', '0004_auto_20220115_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_sheet_reports', to='projects.project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
