# Generated by Django 3.2.9 on 2022-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_dailytimesheet_timesheet_dailytimesheet_unq__date__employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimesheet',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
