# Generated by Django 3.2.9 on 2022-01-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220115_1927'),
        ('timesheet', '0007_alter_dailytimesheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetreport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_sheet_reports', to='projects.category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
