"""
Django settings for timesheet project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

SECRET_KEY = 'django-insecure-kep5b30pbt4y311cu3d0h$k_y=otnv($7%0$(_&g(3j!daoalj'

DEBUG = True

ROOT_URLCONF = 'main.urls'
