# Generated by Django 3.2.8 on 2021-10-30 18:18

from django.db import migrations

sql_query = """
        /* BEGIN; */
        
        CREATE TABLE "core_user" (
           "id" bigserial NOT NULL PRIMARY KEY, 
           "name" varchar(250) NOT NULL, 
           "weekly_hours" double precision NOT NULL, 
           "username" varchar(250) NOT NULL, 
           "email" varchar(250) NOT NULL, 
           "is_active" boolean NOT NULL, 
           "is_admin" boolean NOT NULL
        );
        
        /* COMMIT; */
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql_query),
    ]
