# Generated by Django 3.2.9 on 2021-12-25 08:25

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
            ],
            options={
                'db_table': 'core_daily_time_sheet',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=250, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.BinaryField(default=b'', max_length=500, verbose_name='password')),
                ('weekly_hours', models.FloatField(verbose_name='weekly hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='hours')),
                ('overtime_hours', models.FloatField(default=0, verbose_name='overtime hours')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('daily_time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheet_reports', to='core.dailytimesheet', verbose_name='daily time sheet')),
            ],
            options={
                'db_table': 'core_time_sheet_report',
                'default_related_name': 'time_sheet_reports',
            },
        ),
        migrations.AddField(
            model_name='dailytimesheet',
            name='employee',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='employee'),
        ),
    ]
